# Generated by Django 4.1.7 on 2023-04-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Student',
        ),
    ]
